Add option to skip check
cloudfoundry/bosh-deployment-resource pull request #54
Opened 2018-08-10 11:03 UTC by akshaymankar

Setting this will avoid failing checks when using this resource in dynamic configuration

[Fixes #53]

Signed-off-by: @henderjm

2018-08-17 22:15 UTC, youreddy commented
+1

2018-08-21 12:38 UTC, drich10 requested changes
Could this behavior be moved out of main to somewhere more testable? Main has been intentionally as imperative as possible. A very reasonable location would be `check_command.go`.

2018-08-22 10:38 UTC, henderjm commented
The if check will have to remain in main.go until all bosh related activity is removed from it as creating a director at all causes issue #53 

We originally had in check_command.go with tests but without the if check in main.go it continued to fail.

2018-08-22 11:04 UTC, akshaymankar commented
It might be possible if we move all of this code in `Run()`

```golang
hostKeyGetter := proxy.NewHostKey()
socks5Proxy := proxy.NewSocks5Proxy(hostKeyGetter, log.New(ioutil.Discard, "", log.LstdFlags))
cliCoordinator := bosh.NewCLICoordinator(checkRequest.Source, os.Stderr, socks5Proxy)
commandRunner := bosh.NewCommandRunner(cliCoordinator)
cliDirector, err := cliCoordinator.Director()
if err != nil {
  fmt.Fprint(os.Stderr, err)
  os.Exit(1)
}

director := bosh.NewBoshDirector(
  checkRequest.Source,
  commandRunner,
  cliDirector,
  os.Stderr,
)
```

It might require some funky dependency injection things, i.e. creating an interface for getting a director object, storing it in `CheckCommand` object and faking the interface to test `Run()`. Would you be open to this sort of a PR?

2018-08-23 15:10 UTC, drich10 approved these changes

2018-08-23 15:13 UTC, drich10 commented
Well that is unfortunate, I'll go ahead and get this merged as is then. Don't want y'all to go through that kind of refactoring for this. Look out for this in the next day or so!

2018-08-24 12:37 UTC, merged